shane:
  - name: Thorne Basic Nutrients 2/Day
    amount: 2
  - name: Creatine HCl
    amount: 2
  - name: Glycine
    amount: 1
  - name: Vitamin D3 (1000 IU)
    amount: 1
  - name: SlowMag
    amount: 2
  - name: L-Theanine
    amount: 1
  - name: Apigenin
    amount: 1
