ingredients.append(Ingredient(name: "Coconut Oil", servingSize: 14, calories: 130, fat: 14, fiber: 0, netcarbs: 0, protein: 0, consumptionUnit: Unit.Tablespoon, consumptionGrams: 14, inStock: true))
ingredients.append(Ingredient(name: "Extra Virgin Olive Oil", servingSize: 14, calories: 120, fat: 14, fiber: 0, netcarbs: 0, protein: 0, consumptionUnit: Unit.Tablespoon, consumptionGrams: 14, inStock: true))
ingredients.append(Ingredient(name: "Avocado Oil", servingSize: 14, calories: 130, fat: 14, fiber: 0, netcarbs: 0, protein: 0, consumptionUnit: Unit.Tablespoon, consumptionGrams: 14, inStock: true))
ingredients.append(Ingredient(name: "Fish Oil", servingSize: 5, calories: 40, fat: 4.5, fiber: 0, netcarbs: 0, protein: 0, consumptionUnit: Unit.Tablespoon, consumptionGrams: 14, inStock: true))
ingredients.append(Ingredient(name: "Pumpkin Seeds", servingSize: 28, calories: 160, fat: 14, fiber: 2, netcarb: 1, protein: 8, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Chicken", servingSize: 100, calories: 115, fat: 2.7, fiber: 0, netcarbs: 0, protein: 22, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Beef", servingSize: 100, calories: 214, fat: 15.2, fiber: 0, netcarbs: 0, protein: 19, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Lamb", servingSize: 85, calories: 253, fat: 22, fiber: 0, netcarbs: 0.19, protein: 13.09, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Pork Chop", servingSize: 113, calories: 220, fat: 11, fiber: 0, netcarbs: 0, protein: 30, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Salmon", servingSize: 112, calories: 150, fat: 5, fiber: 0, netcarbs: 0, protein: 25, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Top Sirloin Cap", servingSize: 238, calories: 125, fat: 14, fiber: 0, netcarbs: 0, protein: 51, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Argentine Red Shrimp", servingSize: 110, calories: 100, fat: 1.5, fiber: 0, netcarbs: 0, protein: 21, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Eggs", servingSize: 50, calories: 70, fat: 5, fiber: 0, netcarbs: 0, protein: 6, consumptionUnit: Unit.Egg, consumptionGrams: 50, inStock: true))
ingredients.append(Ingredient(name: "Mackerel", servingSize: 85, calories: 219, fat: 2.9, fiber: 0.2, netcarbs: 0, protein: 22, consumptionUnit: Unit.Gram, consumptionGrams: 85, inStock: true))
ingredients.append(Ingredient(name: "Smoked Sardines", servingSize: 85, calories: 170, fat: 11, fiber: 0, netcarbs: 0, protein: 18, consumptionUnit: Unit.Can, consumptionGrams: 85, inStock: true))
ingredients.append(Ingredient(name: "Sardines", servingSize: 85, calories: 190, fat: 12, fiber: 0, netcarbs: 0, protein: 21, consumptionUnit: Unit.Can, consumptionGrams: 85, inStock: true))
ingredients.append(Ingredient(name: "Tuna", servingSize: 85, calories: 100, fat: 2.5, fiber: 0, netcarbs: 0, protein: 21, consumptionUnit: Unit.Can, consumptionGrams: 85, inStock: true))
ingredients.append(Ingredient(name: "Arugula", servingSize: 20, calories: 5, fat: 0.13, fiber: 0.32, netcarbs: 0.41, protein: 0.52, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Spinach", servingSize: 85, calories: 25, fat: 0.25, fiber: 2, netcarbs: 1, protein: 2, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Collared Greens", servingSize: 36, calories: 12, fat: 0.22, fiber: 1.4, netcarbs: 0.6, protein: 1.09, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Romaine", servingSize: 47, calories: 8, fat: 0.14, fiber: 0.99, netcarbs: 0.51, protein: 0.58, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Broccoli", servingSize: 85, calories: 20, fat: 0, fiber: 3, netcarbs: 1, protein: 2, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Cauliflower", servingSize: 85, calories: 20, fat: 0, fiber: 2, netcarbs: 2, protein: 2, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Mushrooms", servingSize: 35, calories: 8, fat: 0.12, fiber: 0.35, netcarbs: 0.75, protein: 1.1, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Radish", servingSize: 58, calories: 9, fat: 0.06, fiber: 0.93, netcarbs: 1.07, protein: 0.39, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Serrano Pepper", servingSize: 6, calories: 2, fat: 0.03, fiber: 0.23, netcarbs: 0.18, protein: 0.11, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Jalapeno Pepper", servingSize: 14, calories: 4.1, fat: 0.05, fiber: 0.39, netcarbs: 0.52, protein: 0.13, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Avocado", servingSize: 50, calories: 80, fat: 7, fiber: 3.4, netcarbs: 0.9, protein: 1, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "String Cheese", servingSize: 28, calories: 80, fat: 6, fiber: 0, netcarbs: 0, protein: 7, consumptionUnit: Unit.Stick, consumptionGrams: 28, inStock: true))
ingredients.append(Ingredient(name: "Macadamia Nuts", servingSize: 30, calories: 220, fat: 23, fiber: 3, netcarbs: 1, protein: 0, consumptionUnit: Unit.Gram, consumptionGrams: 1, inStock: true))
ingredients.append(Ingredient(name: "Salsa", servingSize: 30, calories: 10, fat: 0, fiber: 1, netcarbs: 0, protein: 1, consumptionUnit: Unit.Tablespoon, consumptionGrams: 15, inStock: true))
ingredients.append(Ingredient(name: "Mustard", servingSize: 5, calories: 5, fat: 0, fiber: 0, netcarbs: 0, protein: 0, consumptionUnit: Unit.Tablespoon, consumptionGrams: 15, inStock: true))
